# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # To upgrade hooks run: `prek autoupdate`
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^uv.lock$
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: format
        name: check and reformat by ruff
        # The pdm/fast/ruff/ty command can be install by:
        #   uv tool install --python 3.14 pdm
        #   uv tool install --python 3.14 fast-dev-cli
        #   uv tool install --python 3.14 ruff
        #   uv tool install --python 3.14 ty
        entry: pdm run fast lint --skip-mypy
        language: system
        types: [python]

      - id: pypi
        name: ensure pypi for uv lock
        files: 'uv.lock'
        entry: pdm run fast pypi --slim
        language: system

      - id: ty-check
        name: check type hints by ty
        entry: pdm run ty check
        language: system
        pass_filenames: false

      - id: mypy
        name: Check type hints by mypy
        entry: just mypy
        language: system
        args: [.]
        pass_filenames: false
        groups: [check]
        stages: [manual]

      - id: build
        name: Build sdist by uv
        entry: uv build
        language: system
        pass_filenames: false
        groups: [check]
        stages: [manual]

      - id: twine
        name: Check sdist by twine
        entry: uvx twine check dist/*
        language: system
        pass_filenames: false
        priority: 20
        groups: [check]
        stages: [manual]
