[project]
name = "fastdfs-client"
description = "Python Implement for FastDFS Client"
authors = [{name="Waket Zheng", email="waketzheng@gmail.com"}]
dynamic = ["version"]
readme = "README.md"
dependencies = [
    "anyio (>=4.0.0,<5.0.0)",
]
requires-python = ">=3.10"
keywords = ["asyncio", "anyio", "FastDFS"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Typing :: Typed",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
homepage = "https://github.com/waketzheng/fastdfs-client-python"
repository = "https://github.com/waketzheng/fastdfs-client-python"
"Bug Tracker" = "https://github.com/waketzheng/fastdfs-client-python/issues/"

[tool.poetry]
version = "0.0.0"  # Managed by poetry-dynamic-versioning
packages = [{ include = "fastdfs_client" }]

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry-dynamic-versioning.from-file]
source = "fastdfs_client/__init__.py"
pattern = '__version__ = "(.+)"'

[tool.pdm.version]
path = "fastdfs_client/__init__.py"

[tool.pdm.build]
excludes = ["./**/.git", "./**/.*_cache", "examples", "scripts", "tests"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "asynctor[testing]>=0.15.2",
    "coverage>=7.16.1",
    "httpx2 (>=2.0,<3.0)",
    "pytest>=9.1.1",
    "trio>=0.34.0",
]

[tool.mypy]
pretty = true
python_version = "3.10"
ignore_missing_imports = true
check_untyped_defs = true

[tool.ruff.lint]
extend-select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "I",      # https://docs.astral.sh/ruff/rules/#isort-i
    "SIM",    # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "FA",     # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
    "UP",     # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "RUF100", # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
]

[tool.ruff.lint.per-file-ignores]
"fastdfs_client/*.py" = [
    "UP031",  # Use format specifiers instead of percent format
    "DTZ006", # `datetime.datetime.fromtimestamp()` called without a `tz` argument
    "BLE001", # Do not catch blind exception: `Exception`
    "RUF009", # Do not perform function call `Struct` in dataclass defaults
]
"*_test.py" = ["E401", "E402", "F403", "F405"]

[tool.ty.src]
exclude = ["scripts/*.py"]

[tool.ty.rules]
unused-ignore-comment = "ignore"
unresolved-attribute = "ignore"

[tool.pyright]
exclude = ["scripts/"]
