# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "docs/**"
      - "*.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12, 3.13, 3.14]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          enable-cache: true
          version: "latest"
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Install ruff without running check or format
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "--version"
      - uses: extractions/setup-just@v4  # Or: uv tool install rust-just
      - name: Setup PDM by uv
        run: |
          uv tool install pdm --with pdm-plugin-i
          pdm config check_update false
          pdm config use_uv true
      - name: Setup fast by uv
        run: uv tool install fast-dev-cli
      - name: Setup ty
        run: uv tool install ty
      - name: Pull submodule justfile
        run: just init http
      - name: Install deps
        run: just install
      - name: Check code style and Type Hint
        run: uvx prek run --all-files --hook-stage manual
      - name: Test with pytest
        run: |
          # TODO: use docker to run unittest
          echo 'just test'
